version: "3.8"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
        - './server:/server'
    expose:
      - 5000
    ports:
      - 5000:5000

  web:
    container_name: web
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
        - './client:/usr/src/app'
        - /usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
       - CHOKIDAR_USEPOLLING=true